In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas
import geopandas as gpd
import datetime as dt
import time

from shapely.geometry import MultiPolygon
from data.test_data_2d import barriers_2d, pts_2d, example_route, example_space, islas
START, END = pts_2d['bc'], pts_2d['tc']

In [27]:
i = np.array([[START.x, START.y],[END.x, END.y]])
#print(i)
print(np.column_stack(i))
p,q = np.column_stack(i)
p

[[291107.6 292653.3]
 [ 53789.1  48962.3]]


array([291107.6, 292653.3])

In [25]:
thing = {'v':None, 'b':1, 'x':5}
{k:v for k, v in thing.items() if v}

{'b': 1, 'x': 5}

In [5]:
import yaml
from pprint import pformat
with open("cfg/default.yml", "r") as cfg:
    ml_config = yaml.load(cfg, Loader=yaml.FullLoader)
    #print(type(config))
#s = pformat(config, indent=4, depth=12)
print(yaml.dump(dict(ml_config), allow_unicode=True, indent=4))
#print(ml_config)

dataset:
    barriers: clokes
    destination: tc
    origin: bc
defaults:
    chunksize: None
    cxpb: 0.5
    elitism: true
    end: 1
    hof_size: 3
    max_height: 8
    max_length: 80
    multiproc: imap
    mutpb: 0.1
    ngen: 250
    nsegs: 100
    patience: 100
    pop_size: 300
    seed: 151
    start: 0
logging:
    no_log: false
    no_record: false
    verbose: false
validation:
    intersection_cost: intersection**2
    invalidity_cost: length*100
    no_intersect: true
    threshold: 2
visualisation:
    gif_zoom: 0.15
    no_plot: false
    save_gif: true
    short_gif: true
    sol_txt: true



In [31]:
config = {}
config.update(list(ml_config.values()))
    
#l_config = {c.key():c.value() for c in ml_config.values()}
print(Namespace(**config))

ValueError: dictionary update sequence element #0 has length 3; 2 is required

In [1]:
from argparse import Namespace

# The 2 initial objects
options_foo = Namespace(foo="foo", bar='foo')
options_bar = Namespace(bar="bar")

# the merged object
options_baz = Namespace(**vars(options_foo), **vars(options_bar))
options_baz

TypeError: argparse.Namespace() got multiple values for keyword argument 'bar'

In [22]:
from argparse import Namespace
ns = Namespace()
ns.option = 'opt'
ns.var = 'vari'
ns.setting = 'set'
print(type(ns))
nsd = vars(ns)
print(type(nsd))
nsd.update(config)
#Namespace(**ns)
vars(ns)

<class 'argparse.Namespace'>


TypeError: 'NoneType' object is not callable

In [7]:
interval = (START.coords[0], END.coords[0])
interval = np.array([list(ele) for ele in list(interval)])
interval

array([[291107.6,  53789.1],
       [292653.3,  48962.3]])

In [8]:
np.array([[START.x, START.y], [END.x ,END.y]])

array([[291107.6,  53789.1],
       [292653.3,  48962.3]])